services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn -w 2 -b 0.0.0.0:5000 wsgi:app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: kartoteka
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
